### ISSUE TITLE
Better support for GitHub Actions

### ISSUE THREAD

**Issue by teohhanhui** [cedx/coveralls.php#7]
I think there's a lot of inspiration to be taken from the official Action: https://github.com/coverallsapp/github-action/blob/master/src/run.ts

**Comment by cedx** [comment]
Could you be more explicit about what could be improved?
I don't intend to implement a real GitHub action: there is already the one you mentioned (https://github.com/marketplace/actions/coveralls-github-action).

For using this package as is with GitHub Actions, the workflow can be summarized by:

```yaml
on:
  push
jobs:
  test:
    steps:
      - uses: actions/checkout@v1
      - run: composer install --no-interaction
      - run: ./vendor/bin/phpunit
      - env:
          COVERALLS_REPO_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: ./vendor/bin/coveralls path/to/coverage.xml
```
